### ISSUE TITLE
Email received but no tickets available

### ISSUE THREAD

**Issue by sammy88888888** [joshcarty/ra-resale#1]
Hey man! Love the app but sometimes when I sign up I get an email very quickly but no tickets are available. Any thoughts? Event in question: https://www.residentadvisor.net/events/1290237

**Comment by joshcarty** [comment]
Hey! Thanks - out of interest, how did you hear about it?

I’m on holiday so can’t dig very deep but I know that lots of people are subscribed to alerts for that event. I think there’s a good chance someone else is buying the ticket in the time between performing the check, sending the email, and you going to buy?

Sorry I can’t be of any more help!

**Comment by sammy88888888** [comment]
That's ok, I kind of figured that might be the case. Wondering if a solution might be to include the number of people the email is being sent out to?

Not sure how I found out about it. Just couldn't believe RA didn't provide that service so did a bit of Googling :)

**Comment by joshcarty** [comment]
Love the idea of including the number of people watching - that’s definitely doable!

FYI there are 9 people who’ve subscribed to tickets for Homobloc but all have had an email sent to them. Not sure if this is clear, but you have to resubscribe once you’ve received an email (to avoid receiving emails once you’ve got a ticket).

If you re-add your email now (can be the same email) you’ll be the only one getting alerts.

Also, I subscribed to Homobloc alerts to test it yesterday and the alert went to my spam so watch out for that.

**Comment by mjkdubai** [comment]
His Josh! Thanks for the amazing service. The watch count would be amazing. Also, maybe get an email confirmation that I am subscribed to the list for the event? 
Cause I did sign up for it, and for the past week I was checking the event page like crazy waiting for tickets to pop up, but I didn’t know if this working or not. While if I got an email confirming it would’ve been less stressful for me haha!

Amazing service, found it on google cause it didn’t make sense to me that I would have to refresh RA every 5 minutes to find tickets

**Comment by joshcarty** [comment]
Good idea with an email confirmation - that would help address some of the issues with emails going to spam too.

**Comment by MetcalfeTom** [comment]
@joshcarty I got the same thing - email about the event without tickets being available.

I tested your code locally and `extract_availability()` works as expected so I'm not sure why it happens 🤔

**Comment by joshcarty** [comment]
Yeah I’ve experienced this too but haven’t been able to figure out what’s going wrong. I think what happens is a ticket is marked as available but isn’t correctly reset when a new user signs up.

Appreciate you checking the extraction - that was my first thought too!

**Comment by MetcalfeTom** [comment]
@joshcarty Good shout, my PR should fix this issue then.

**Comment by joshcarty** [comment]
@MetcalfeTom Aha - yeah this could do it! Good catch. I’ll be able to merge / deploy this tomorrow. Thanks!
