### ISSUE TITLE
Question - Test Email to Ensure Delivery + Not Spam?

### ISSUE THREAD

**Issue by andre9017** [joshcarty/ra-resale#12]
Hi there,

This is an excellent idea and a great project, well done.

I was just wondering if there was functionality to do a test delivery email, or even a confirmation email of altert being set up? This sort of tool would fall down if the notifying email was sent to spam and/or failed to get delivered, so some sort of confirmation from your sending address would give good confidence.

Just a suggestion....

Thanks
Andre

**Comment by joshcarty** [comment]
Hey @andre9017 - thanks for the suggestion.

It would definitely be annoying if the email went to spam. However, if possible, I want to avoid sending conformation emails. The main reason is that it would at least double (likely much more) the total number of emails sent. If anything I think that would increase the chance that they are marked as spam.

Once you receive an email alert, you can mark the sender as safe to reassure yourself it can never go to spam. The email address is hardly a secret but I'm not sure how I feel about posting it here or on the site for spammers to scrape. Sorry if that's needlessly paranoid on my part lol.

For what it's worth, I've never had an email go to spam in all the time I've used or tested the tool. I know how stressful it can be looking for tickets but I think confirmation emails would introduce more issues than they would solve.

Thanks!

**Comment by joshcarty** [comment]
Actually, seen the email is [here](https://github.com/joshcarty/ra-resale/blob/master/alerts/views.py#L238) if you want to add it to an approve list.
