### ISSUE TITLE
Could not extract ticket information from RA

### ISSUE THREAD

**Issue by maudeinhorn** [joshcarty/ra-resale#7]
Heya, 

I'm trying to use the app to get resale tickets for a couple of events but in all cases it isn't able to extract the ticket information from RA - I'm not sure if this is because RA recently had an overhaul of their website?

Just wondering if you could look into this, and also whether it would be possible to specify the type of ticket you are looking for resale alerts on e.g. in the case where the main festival tickets have sold out but you can still buy car parking tickets (https://ra.co/events/1326673#tickets)

Cheers in advance!

![Screenshot 2021-03-11 at 14 37 42](https://user-images.githubusercontent.com/41071462/110804269-ec2ca500-8277-11eb-80e4-1d05572e2300.png)

**Comment by bs13053** [comment]
I'm actually experiencing exactly the same issue as you Maud

**Comment by dafyddjsinden** [comment]
As am I... are we all hoping to go to Houghton?

**Comment by joshcarty** [comment]
Hey - yeah so RA redesigning the site understandably broke a bunch of stuff. Keen to fix it too but I need to figure out how the new site works.

Can you even tell that tickets are on resale? I didn't think every event had it and the old site had a "Resale Active" label. Have Houghton said that tickets would be resold through RA?

**Comment by joshcarty** [comment]
Oh right, seen on Facebook they're definitely doing resale. Hmm that's annoying you can't see that resale is active. I'm not really keen on having trackers for any event regardless of whether resale is active or not. I'll need to think about that some more.

In the meantime, you could try one of those browser extensions that let you monitor pages? Haven't used them before but mates have had luck with them. Maybe [this](https://chrome.google.com/webstore/detail/distill-web-monitor/inlikjemeeknofckkjolnjbpehgadgge?hl=en) or [this](https://chrome.google.com/webstore/detail/visualping/pemhgklkefakciniebenbfclihhmmfcd?hl=en).

Good luck - I know what it's like trying to get sold out tickets.

**Comment by maudeinhorn** [comment]
I've actually managed to get something working based on [this](https://github.com/12ian34/rattata) but its not super user friendly - i'm running a script in a tmux session where i've given it the event and specific ticket type and having it alert me when that comes up on sale. They have figured out accessing all the ticket info from the new RA site though so that might help you?

Not sure how you get around detecting whether resale is active in the first place though as RA do seem to have taken that away completely. 

Yeah its a bit of a nightmare... Appreciate you looking into it though! Sure all the above will be über grateful if you get it working

**Comment by joshcarty** [comment]
Haven't had time to properly look at this, but I've seen that some events like [this](https://ra.co/events/1433199) do have a "resale active" message:

>**About resale**
This event has sold out and the resale queue is active.
Check back to purchase tickets as they become available.

It's weird that [Houghton](https://ra.co/events/1326673) doesn't. Does anyone know of someone that's bought through resale?

**Comment by maudeinhorn** [comment]
I don't know anyone who has yet, but I did get a notification the other night from the script I mentioned above saying that one had come up for sale but it had sold by the time I woke up unfortunately. 

I'm pretty sure resale is active for the sold out tickets but RA are maybe only putting the "resale active" message on event pages if the entire event has sold out. So Houghton doesn't have it because there are other tickets i.e. car parking tickets which are still on sale?

**Comment by dafyddjsinden** [comment]
I managed to get a ticket through resale just after I commented above, hence my lack of attention to this thread - hope that clarifies that tickets are indeed being resold!

**Comment by bs13053** [comment]
@joshcarty you'll be our hero if you can get this working again :)

**Comment by joshcarty** [comment]
Thanks everyone! Small update (don't get excited yet):

The [site](https://ra-resale.appspot.com/) back up and I've updated it to work with the new address and page layout. However, it's checking that resale is active from the "resale active" message mentioned above. That means it will only work for events like [this](https://ra.co/events/1433199) or [this](https://ra.co/events/1438324).

Not quite sure how it will need to work for events like Houghton that don't have the resale active message and are still selling other tickets. You'll have to subscribe to a particular ticket which is new and different. It's doable but will take a bit more time.

Thanks for the tips that resale is definitely active. I think you could be right @maudeinhorn that they don't put the message up until it's fully sold out. However, I want a ticket for [Field Maneuvers](https://ra.co/events/1333884) and it's sold out and [apparently](https://www.fieldmaneuvers.com/faqs) doing resale, but still no message - annoying.

**Comment by mjkdubai** [comment]
Sorry to get into this, but I already brought this issue up (resell active) more than a year ago.
RA have many events like Houghton that they have resell active while they don't have that label. I was looking to an event that it was sure sold out because it was 100 ppl capacity. But you couldve post your ticket back to sell on RA.

So please Josh, I am asking you to look into this issue. 

Thanks in advance

**Comment by bs13053** [comment]
Great news @joshcarty! I've got it up and running and seems to be working :) 
One interesting scenario - https://ra.co/events/1336874 - this event (Gala) is sold out but the process isn't working - it's as if they haven't marked resale as active even though it is from what I can tell. Can you have a look? 

Update - I see on the above you mentioned examples that are doing this exact same issue

**Comment by finski-maker** [comment]
> I managed to get a ticket through resale just after I commented above, hence my lack of attention to this thread - hope that clarifies that tickets are indeed being resold!

Just through the main resale site by chance? Surprise surprise I am also after a Houghton ticket haha

- also appreciate all the hard work put in @joshcarty !

**Comment by tomhemming98** [comment]
Facing similar issues at mentioned above. (Looking for Houghton tickets...) It appears that since RA updated their website they changed how resale operates. Thanks a lot for this program. It would be life saving if it could be updated to operate correctly given the new layout.

**Comment by dafyddjsinden** [comment]
> > I managed to get a ticket through resale just after I commented above, hence my lack of attention to this thread - hope that clarifies that tickets are indeed being resold!
> 
> Just through the main resale site by chance? Surprise surprise I am also after a Houghton ticket haha
> 
> * also appreciate all the hard work put in @joshcarty !

Yup - through RA resale. I just refreshed the page and the option to purchase a ticket was active once again. I'm pretty sure that's how RA resale used to work, too, before they updated their frontend. (As a side note, Houghton emphasise that they don't support tickets resold through touts, so definitely stay away from any third party resales as there's no guarantee that tickets sold through them will be accepted on the day).

**Comment by joshualant** [comment]
Hi all.

I wrote a script which does something similar to this when I couldn't get this tool installed and running (prior to the recent update), but only specifically for the Houghton event page (I will not share currently as it is disgusting to look at).

However, my solution uses selenium, which is very slow as it fires up full headless Firefox instances.

So to make it quicker I have tried using the method in the link that @maudeinhorn posted, using lxml etree API within my own script, but was running into a problem when getting the HTML using python's "requests" library.

The ticket box on the page is inside a separate HTML document in an iframe on the page. The issue is that when trying to access stuff inside this iframe's url from the main event page (also when you try to open it directly in a new browser tab) the response I get is access denials from cloudflare.

It seems their servers are preventing me from getting the contents of that iframe (at URL https://ra.co/widget/event/ <event_id> /embedtickets) unless I go through a proper browser (which is why the selenium solution works). So I guess there is an issue that I am not forming proper HTTPS requests that i am creating from this "requests" library? 

However, the relevant information to parse to see if any of the tickets are available is directly available at links like this (this is how it is generated in that script that @maudeinhorn posted): 

https://ra.co/widget/event/ <event_id>

Using the requests library on this url gives no access denials, so you can then parse the information you need from there.

The very very dirty way I get around the Houghton style page (where other tickets are still available to buy) is to check for the element in the list that costs the most, and see whether that is "closed" or "onsale-but", as any resale tickets will be sold in the highest price bracket surely?

Anyway, I hope this helps. Good luck on the ticket hunt!!

**Comment by joshcarty** [comment]
Thanks for the posts everyone.

@joshualant thanks, that's great info - sounds like you've figured it out. As a tip, an alternative to using Selenium would be to supply a user agent in `requests`. You can see that [here](https://github.com/joshcarty/ra-resale/blob/524aea85e87a07a0e40388b2bec1c5c0b39095e6/alerts/__init__.py#L16), or in the script @maudeinhorn posted [here](https://github.com/12ian34/rattata/blob/a9d555dc6b78025ae44685db6af89c5234c16996/ra-ticket-resale-watch.py#L25). Interesting that you don't need to for the `/widget` link though. Nice idea on using the price to ignore parking too. Would be great if you could post your script - who cares if it's hacky.

Here's my current plan for solving Houghton tickets:

1. Change the "Resale Active" check to instead look for events that are fully sold out. That will solve [GALA](https://ra.co/events/1336874) (@bs13053) and [FM](https://ra.co/events/1333884) that are sold out but not showing the resale active message.
2. Add a way to manually ignore certain ticket types. That seems like the simplest way to solve this Houghton parking tickets thing. The alternative of adding tracking for particular tickets would be quite a bit more work for what seems like a rare case.  I'll have to manually set which tickets to exclude but that should be fine if this sort of event its rare.

Hopefully should get 1. done this evening and can look at 2. later this week.

**Comment by joshcarty** [comment]
I've made the change to the resale active check that means it will now work for events that don't have the "resale queue is active" label. The event just needs to be fully sold out.

I know lots of you are after Houghton tickets that is technically not "fully sold out" because of those parking tickets. You'll have to wait a little longer for me to solve that as above.

**Comment by joshcarty** [comment]
Right - after that all that, the [site](https://ra-resale.appspot.com/) should now be working for [Houghton](https://ra.co/events/1326673).

You can subscribe to alerts using the page link as usual and you'll only get an email when one of the non parking or live-in tickets become available. Remember, you'll need to resubscribe if you receive the email but don't manage to buy the ticket in time.

This works by me manually setting certain tickets to be ignored. It's easy to do though so, if there is another event that needs it, someone will need to create an issue like this and I can do it.

Good luck with getting tickets!
@maudeinhorn @joshualant @finski-maker @tomhemming98 @bs13053  @mjkdubai

**Comment by headtopmusic** [comment]
You'll be a hero if you can get this to work!

**Comment by bs13053** [comment]
@joshcarty AMAZING it's working!!! genuinely thank you for all the effort you put in the past few days getting this working again :) game changer

**Comment by headtopmusic** [comment]
You're a hero @joshcarty. Thanks for making this!

**Comment by maudeinhorn** [comment]
Thanks a bunch @joshcarty!

**Comment by tomhemming98** [comment]
Legend @joshcarty, can't thank you enough! Hope to see all above in a field in Northfolk... best of luck!

**Comment by mjkdubai** [comment]
Thank you so much @joshcarty you're a living legend

**Comment by maudeinhorn** [comment]
Hey again @joshcarty. I have another annoying RA resale issue.

Would it be possible to have an alert set up for the regular tickets on this event: https://ra.co/events/1342426. As the VIP/afterparty have not sold out the resale queue isn't active (similar situation as Houghton). Don't worry if it's a hassle and thanks again!!

**Comment by joshcarty** [comment]
Hey! Set it now to ignore those VIP and After Party tickets. Think there's a Final Release up now actually!

**Comment by yellowcakes** [comment]
Love your work.

Would it be possible to add a manual ignore for [GALA ](https://ra.co/events/1336874) as I'm after a Saturday ticket but there are currently weekend and Sunday tickets still available. 

Thanks in advance.

**Comment by joshcarty** [comment]
@yellowcakes really sorry, I was on holiday when this came through and it totally skipped my mind. I hope you were able to get a ticket for today.
